# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
    app.cat_namer:
        class: AppBundle\DependencyInjection\CatNamerInterface

    app.task_controller:
        class: AppBundle\Controller\TaskController

    app.heroku_scheduler:
        class: AppBundle\EventListener\HerokuSchedulerListener
        arguments: [ @twig, @mailer, @service_container ]
        tags:
            - { name: kernel.event_listener, event: heroku_daily }
